name: template_python
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - appnope=0.1.0
  - arrow-cpp=0.15.1
  - attrs=19.3.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - boost-cpp=1.69.0
  - brotli=1.0.7
  - bzip2=1.0.8
  - c-ares=1.15.0
  - ca-certificates=2020.1.1
  - certifi=2019.11.28
  - dbus=1.13.12
  - decorator=4.4.1
  - defusedxml=0.6.0
  - double-conversion=3.1.5
  - expat=2.2.6
  - gettext=0.19.8.1
  - gflags=2.2.2
  - glib=2.56.2
  - glog=0.4.0
  - grpc-cpp=1.26.0
  - icu=58.2
  - importlib_metadata=1.5.0
  - intel-openmp=2019.4
  - ipykernel=5.1.4
  - ipython=7.12.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.16.0
  - jinja2=2.11.1
  - joblib=0.14.1
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=5.3.4
  - jupyter_console=6.1.0
  - jupyter_core=4.6.1
  - libboost=1.67.0
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libevent=2.1.10
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libiconv=1.15
  - libpng=1.6.37
  - libprotobuf=3.11.2
  - libsodium=1.0.16
  - llvm-openmp=4.0.1
  - lz4=3.0.2
  - lz4-c=1.8.3
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - ncurses=6.2
  - notebook=6.0.3
  - numpy-base=1.18.1
  - openssl=1.1.1d
  - pandas=1.0.1
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.6.1
  - pcre=8.43
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.0.2
  - prometheus_client=0.7.1
  - prompt_toolkit=3.0.3
  - ptyprocess=0.6.0
  - pyarrow=0.15.1
  - pygments=2.5.2
  - pyqt=5.9.2
  - pyrsistent=0.15.7
  - python=3.7.6
  - python-dateutil=2.8.1
  - pytz=2019.3
  - pyzmq=18.1.1
  - qt=5.9.7
  - qtconsole=4.6.0
  - re2=2019.09.01
  - readline=7.0
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - send2trash=1.5.0
  - setuptools=45.2.0
  - sip=4.19.13
  - six=1.14.0
  - snappy=1.1.7
  - sqlite=3.31.1
  - terminado=0.8.3
  - testpath=0.4.4
  - thrift-cpp=0.11.0
  - tk=8.6.8
  - tornado=6.0.3
  - traitlets=4.3.3
  - uriparser=0.9.3
  - wcwidth=0.1.8
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - xz=5.2.4
  - zeromq=4.3.1
  - zipp=2.2.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - alembic==1.4.0
    - azure-common==1.1.24
    - azure-storage-blob==2.1.0
    - azure-storage-common==2.1.0
    - cffi==1.14.0
    - chardet==3.0.4
    - click==7.0
    - cloudpickle==1.3.0
    - configparser==4.0.2
    - cryptography==2.8
    - databricks-cli==0.9.1
    - docker==4.2.0
    - entrypoints==0.3
    - flask==1.1.1
    - gitdb==4.0.2
    - gitpython==3.1.0
    - gorilla==0.3.0
    - gunicorn==20.0.4
    - idna==2.9
    - itsdangerous==1.1.0
    - mako==1.1.1
    - mlflow==1.6.0
    - numpy==1.18.1
    - prometheus-flask-exporter==0.12.2
    - protobuf==3.11.3
    - pycparser==2.19
    - python-editor==1.0.4
    - pyyaml==5.3
    - querystring-parser==1.2.4
    - requests==2.23.0
    - simplejson==3.17.0
    - smmap==3.0.1
    - sqlalchemy==1.3.13
    - sqlparse==0.3.0
    - tabulate==0.8.6
    - urllib3==1.25.8
    - websocket-client==0.57.0
    - werkzeug==1.0.0

